#!/bin/sh

SCRIPTROOT=/usr/local/www/remote
LOGROOT=/var/log/rptinderbox

echo "Content-Type: text/plain"
echo ""

TYPE=`echo ${QUERY_STRING} | cut -d'&' -f 1 | cut -d'=' -f 2`
REPOSITORY=`echo ${QUERY_STRING} | cut -d'&' -f 2 | cut -d'=' -f 2`
REVISION=`echo ${QUERY_STRING} | cut -d'&' -f 3 | cut -d'=' -f 2`
BUILD=`echo ${QUERY_STRING} | cut -d'&' -f 4 | cut -d'=' -f 2`

printf "[%s] %s - %s\n" "`date`" "checkout" "${QUERY_STRING}" >> "${LOGROOT}/${BUILD}.log"
${SCRIPTROOT}/rptinderbox checkout "${TYPE}" "${REPOSITORY}" "${REVISION}" "${BUILD}" | tee -a "${LOGROOT}/${BUILD}.log"

exit 0

