#!/bin/sh

SCRIPTROOT=/usr/local/www/remote
LOGROOT=/var/log/rptinderbox

echo "Content-Type: text/plain"
echo ""

PORT=`echo ${QUERY_STRING} | cut -d'&' -f 1 | cut -d'=' -f 2`
BUILD=`echo ${QUERY_STRING} | cut -d'&' -f 2 | cut -d'=' -f 2`
PRIORITY=`echo ${QUERY_STRING} | cut -d'&' -f 3 | cut -d'=' -f 2`
FINISHURL=`echo ${QUERY_STRING} | cut -d'&' -f 4 | cut -d'=' -f 2`

printf "[%s] %s - %s\n" "`date`" "build" "${QUERY_STRING}" >> "${LOGROOT}/${BUILD}.log"
${SCRIPTROOT}/rptinderbox build "${PORT}" "${BUILD}" "${PRIORITY}" "${FINISHURL}" | tee -a "${LOGROOT}/${BUILD}.log"

exit 0

