#!/bin/sh

. cgi.subr
. poudriere.subr

# ARG:
# port:      port origin
# build:     build name
# priority:  priority of the job
# finishurl: callback handler

callhandler "${build}" poudriere_build "${port}" "${build}" "${priority}" "${finishurl}"

