#!/bin/sh

. cgi.subr
. poudriere.subr

type=`getparam $1 type`
repository=`getparam $2 repository`
revision=`getparam $3 revision`
build=`getparam $4 build`

callhandler "${build}" poudriere_checkout "${type}" "${repository}" "${revision}" "${build}"

