#!/bin/sh

. cgi.subr
. poudriere.subr

# type:       checkout type svn/svn-full/git
# repository: repository url
# revision:   revision id
# build:      build to use

callhandler "${build}" poudriere_checkout "${type}" "${repository}" "${revision}" "${build}"

