#!/bin/sh

#
# RedPorts User creation script
#
# $Id$
#

HTPASSWD=/var/db/trac/redports/conf/htpasswd
SVNACCESS=/var/db/trac/redports/conf/svnaccess
TMP=/tmp/redportsrepo

USER=$1
REPOSITORY=file:///var/subversion/redports
SVNUSER=redports

DBNAME=trac
DBUSER=trac

if [ -z "$USER" ]; then
    echo "Usage: rpcreateaccount <username>"
    exit 1
fi

if ! egrep "^${USER}:" ${HTPASSWD} >/dev/null ; then
    echo "User ${USER} does not exist"
    exit 1
fi

# create svn folder for user
rm -rf ${TMP}
svn checkout --username ${SVNUSER} --non-interactive --non-recursive ${REPOSITORY} ${TMP} >/dev/null && \
svn update --non-interactive ${TMP}/${USER} >/dev/null

if [ $? != 0 ]; then
    echo "Repository checkout failed"
    exit 1
fi

if [ ! -d "${TMP}/${USER}" ]; then
    mkdir ${TMP}/${USER} && \
    svn add ${TMP}/${USER} >/dev/null && \
    svn commit --username ${SVNUSER} --non-interactive --message "Welcome ${USER}!" ${TMP}/${USER} >/dev/null

    if [ $? != 0 ]; then
        echo "Failed creating SVN directory"
        exit 1
    fi
else
    echo "SVN directory already exists"
fi

rm -rf ${TMP}


# grant permissions on it
if ! egrep "^\[/${USER}\]" ${SVNACCESS} >/dev/null ; then
    echo "[/${USER}]" >> ${SVNACCESS}
    echo "${USER} = rw" >> ${SVNACCESS}
    echo "" >> ${SVNACCESS}
else
    echo "SVN permissions already granted"
fi

# require email verification for user
SQL=`printf "SELECT value FROM session_attribute WHERE sid = '%s' and name = 'email' and value = (SELECT value FROM session_attribute WHERE sid = '%s' AND name = 'email_verification_sent_to');" "${USER}" "${USER}"`

EMAIL=`echo "${SQL}" | psql -qtA ${DBNAME} ${DBUSER}`

if [ -z "${EMAIL}" ]; then
   SQL=`printf "INSERT INTO session_attribute VALUES ('%s', '1', 'email_verification_token', SUBSTRING(MD5(RANDOM()::text), 1, 10));" "${USER}"`

   echo "${SQL}" | psql -qtA ${DBNAME} ${DBUSER}
else
   echo "EMail is verified: ${EMAIL}"
fi

exit 0
