#!/bin/sh

#
# RedPorts Subversion post-commit hook script
#
# $Id$
#

PATH=${PATH}:/usr/local/bin

REPOSITORYID=1
PRIORITY=7
DBNAME=trac
DBUSER=trac

if [ -z "${1}" -o -z "${2}" ]; then
    echo "Usage: rpaddcommit <repository> <revision>"
    exit 1
fi

REPOS=$1
REV=$2
USER=`svnlook author -r ${REV} ${REPOS}`

# add affected ports to buildqueue
for PORT in `svnlook changed ${REPOS} -r ${REV} | grep -v "D   " | cut -b5- | cut -d'/' -f2-3 | uniq`
do
    START=`date +"%s"`000000
    TMP=`echo "${PORT}" | cut -d'/' -f2`

    # skip lines with category only
    if [ ! -n "${TMP}" ]; then
        echo "Skipping ${PORT}"
        continue;
    fi

    # skip commits to Mk
    if [ "${TMP}" = "Mk" ]; then
        continue;
    fi

    BUILDDATE=`date "+%Y%m%d%H%M%S"`
    RAND=`hexdump -n2 -e\"%u\" /dev/random`
    BUILDID=${BUILDDATE}-${RAND}

    SQLCMD=`printf "INSERT INTO buildqueue (id, owner, repository, revision, portname, status, priority, startdate, enddate) VALUES ('%s', '%s', %d, %d, '%s', %d, %d, %d);" "${BUILDID}" "${USER}" ${REPOSITORYID} ${REV} "${PORT}" 10 ${PRIORITY} ${START} 0`

    echo ${SQLCMD} | psql -q ${DBNAME} ${DBUSER}
    if [ $? != 0 ]; then
        echo "ERROR: Failed adding ${PORT} with r${REV} to buildqueue"
    else
        echo "Added ${PORT} with r${REV} to buildqueue"
    fi
done

exit 0
