#!/bin/sh

#
# RedPorts Subversion post-commit hook script
#
# Date:    2011-03-25 13:00
# Author:  Bernhard Froehlich <decke@FreeBSD.org>
#

PATH=${PATH}:/usr/local/bin

DBNAME=trac
DBUSER=root
LOG=/var/log/redports.log

REPOS=$1
REV=$2
REPOSITORY=${REPOS%${REPOS##*/}}
USER=`svnlook author -r ${REV} ${REPOS}`

# add affected ports to buildqueue
for PORT in `svnlook changed ${REPOS} -r ${REV} | cut -b5- | cut -d'/' -f2-3 | uniq`
do
    REPOSITORYPATH=`svnlook changed ${REPOS} -r ${REV} | cut -b5- | cut -d'/' -f1 | uniq`
    REPOSITORYBASE=${REPOSITORY}${REPOSITORYPATH}
    START=`date +"%s"`000000
    TMP=`echo "${PORT}" | cut -d'/' -f2`

    # skip lines with category only
    if [ ! -n "${TMP}" ]; then
        echo "Skipping ${PORT}"
        continue;
    fi

    # skip commity to Mk
    if [ "${TMP}" = "Mk" ]; then
       continue;
    fi

    echo "INSERT INTO buildqueue (owner, repository, revision, portname, status, startdate, enddate) VALUES (\"${USER}\", \"${REPOSITORYBASE}\", ${REV}, \"${PORT}\", \"committed\", ${START}, 0);" | mysql -u ${DBUSER} ${DBNAME}
    if [ $? != 0 ]; then
        echo "ERROR: Failed adding ${PORT} with r${REV} to buildqueue"
    else
        echo "Added ${PORT} with r${REV} to buildqueue"
    fi
done

exit 0
