#!/bin/sh

SVNUSER=
SVNPASS=
SVNROOT=http://svn.beta.redports.org/${SVNUSER}

PR=$1
PATCH=$2
PORT=$3
SUBJECT=$4

PORTSTREE=/usr/ports
SCRIPTROOT=`pwd`
SCRIPT=`basename $0`
TMPDIR=`mktemp -d /tmp/${SCRIPT}.prbot.XXXXXX` || exit 1

cd ${TMPDIR} || exit 1

if [ -z "${PATCH}" ]; then
   PATCH=1
fi

PORT=`${SCRIPTROOT}/rpfetchpr ${PR} ${PATCH} ${PORT}`
if [ $? -ne 0 ]; then
   echo ${PORT}
   exit 1
fi

PORTCATEGORY=${PORT%${PORT##*/}}

if [ -f "${TMPDIR}/${PR}.diff" ]; then
   if [ ! -d "${PORTSTREE}/${PORT}" ]; then
      echo "Port ${PORT} not found"
      exit 1
   fi

   # checkout repository
   svn co -q --non-interactive ${SVNROOT} ${TMPDIR}/ports || exit 1

   # cleanup repository
   if ls ${TMPDIR}/ports/* >/dev/null 2>&1 ; then
      svn rm -q --non-interactive ${TMPDIR}/ports/* || exit 1

      svn ci -q --non-interactive --username ${SVNUSER} --password ${SVNPASS} \
             --message "Cleanup repository" ${TMPDIR}/ports || exit 1
   fi

   # copy port from porstree to our svn repo
   mkdir -p ${TMPDIR}/ports/${PORT}
   cp -pR ${PORTSTREE}/${PORT}/ ${TMPDIR}/ports/${PORT}
   svn add -q --non-interactive ${TMPDIR}/ports/* || exit 1

   echo "Add ${PORT}" > ${TMPDIR}/ci
   echo "" >> ${TMPDIR}/ci
   echo "Redports: ignore" >> ${TMPDIR}/ci

   svn ci -q --non-interactive --username ${SVNUSER} --password ${SVNPASS} \
          --file ${TMPDIR}/ci ${TMPDIR}/ports || exit 1

   # apply user patch to our svn repo
   patch -d ${TMPDIR}/ports -t -p0 -us < ${TMPDIR}/${PR}.diff || exit 1

   # cleanup .orig files
   find ${TMPDIR}/ports -iname "*.orig" -exec rm {} \;

   # remove empty files
   find ${TMPDIR}/ports -size 0c -exec svn rm --force {} \;
   
   # commit our patched port
   svn add -q --non-interactive --force ${TMPDIR}/ports/* || exit 1

   if [ -z "${SUBJECT}" ]; then
      echo "${PORT}" > ${TMPDIR}/ci
   else
      echo "${PORT}:" > ${TMPDIR}/ci
      echo "${SUBJECT}" >> ${TMPDIR}/ci
   fi
   echo "" >> ${TMPDIR}/ci
   echo "PR:	ports/${PR}" >> ${TMPDIR}/ci
   
   svn ci -q --non-interactive --username ${SVNUSER} --password ${SVNPASS} \
          --file ${TMPDIR}/ci ${TMPDIR}/ports || exit 1

elif [ -f "${TMPDIR}/${PR}.sh" ]; then
   # checkout repository
   svn co -q --non-interactive ${SVNROOT} ${TMPDIR}/ports || exit 1

   # cleanup repository
   if ls ${TMPDIR}/ports/* >/dev/null 2>&1; then
      svn rm -q --non-interactive ${TMPDIR}/ports/* || exit 1

      svn ci -q --non-interactive --username ${SVNUSER} --password ${SVNPASS} \
             --message "Cleanup repository" ${TMPDIR}/ports || exit 1
   fi

   # extract shar script
   mkdir -p ${TMPDIR}/ports/${PORTCATEGORY}
   cd ${TMPDIR}/ports/${PORTCATEGORY}
   sh ${TMPDIR}/${PR}.sh || exit 1

   # commit our patched port
   svn add -q --non-interactive ${TMPDIR}/ports/${PORTCATEGORY} || exit 1

   if [ -z "${SUBJECT}" ]; then
      echo "${PORT}" > ${TMPDIR}/ci
   else
      echo "${PORT}:" > ${TMPDIR}/ci
      echo "${SUBJECT}" >> ${TMPDIR}/ci
   fi
   echo "" >> ${TMPDIR}/ci
   echo "PR:	ports/${PR}" >> ${TMPDIR}/ci
   
   svn ci -q --non-interactive --username ${SVNUSER} --password ${SVNPASS} \
          --file ${TMPDIR}/ci ${TMPDIR}/ports || exit 1

else
   echo "PR does not have a patch"
fi

rm -Rf ${TMPDIR}

exit 0
