#!/bin/sh

LOGDIR=/tmp/rpwatchpr
PRDIR=${LOGDIR}/PR
THISPR=${LOGDIR}/prlist.log
LASTPR=${LOGDIR}/prlist.log.bak
TMPPR=`mktemp /tmp/rpwatchpr.fetch.XXXXXX` || exit 1

if [ "$1" = "update" ]; then
   if [ ! -d "${LOGDIR}" ]; then
      mkdir -p ${LOGDIR}
   fi

   if [ ! -d "${PRDIR}" ]; then
      mkdir -p ${PRDIR}
   fi
      

   fetch -qo ${TMPPR} "http://www.freebsd.org/cgi/query-pr-summary.cgi?category=ports" || exit 1

   if [ ! -f "${LASTPR}" ]; then
      touch ${LASTPR}
   fi

   if [ -f "${THISPR}" ]; then
      mv ${THISPR} ${LASTPR}
   fi

   fgrep "<td><a href='/cgi/query-pr.cgi?pr=" ${TMPPR} > ${THISPR}
fi

diff ${LASTPR} ${THISPR} | grep "^>" | while read LINE
do
   PR=`echo ${LINE} | cut -d'/' -f8 | cut -d"'" -f1`
   DATE=`echo ${LINE} | cut -d'>' -f6 | cut -d'<' -f1`
   SUBJECT=`echo ${LINE} | cut -d'>' -f14 | cut -d'<' -f1`

   echo "-----------------------------------" | tee -a ${PRDIR}/${PR}.log
   echo `date` | tee -a ${PRDIR}/${PR}.log
   echo "PR:      ${PR}" | tee -a ${PRDIR}/${PR}.log
   echo "DATE:    ${DATE}" | tee -a ${PRDIR}/${PR}.log
   echo "SUBJECT: ${SUBJECT}" | tee -a ${PRDIR}/${PR}.log
   echo "" | tee -a ${PRDIR}/${PR}.log

   if fgrep " ${PR} " ${LOGDIR}/success.log >/dev/null 2>&1 ; then
      echo "PR already successfully scheduled. skipping"
   elif [ `echo ${DATE} | cut -d'/' -f1` != "2012" ]; then
      echo "PR too old. skipping"
   else
      ./rpcommitpr "${PR}" "1" "" "${SUBJECT}" | tee -a ${PRDIR}/${PR}.log 2>&1

      if [ $? -eq 0 ]; then
         echo "success."
         echo `date` ${DATE} ${PR} ${SUBJECT} >> ${LOGDIR}/success.log
      else
         echo "failed."
         echo `date` ${DATE} ${PR} ${SUBJECT} >> ${LOGDIR}/failed.log
      fi
   fi
done

exit 0

