#!/bin/sh

#
# RedPorts Subversion post-commit hook script
#
# $Id$
#

PATH=${PATH}:/usr/local/bin

REPOSITORYID=1
PRIORITY=7
DBNAME=trac
DBUSER=trac

if [ -z "${1}" -o -z "${2}" ]; then
    echo "Usage: rpaddcommit <repository> <revision>"
    exit 1
fi

REPOS=$1
REV=$2
USER=`svnlook author -r ${REV} ${REPOS} 2>/dev/null`

if [ -z "${USER}" ]; then
    echo "Invalid revision number"
    exit 1
fi

# add affected ports to buildqueue
for PORT in `svnlook changed ${REPOS} -r ${REV} | grep -v "D   " | cut -b5- | cut -d'/' -f2-3 | uniq`
do
    START=`date +"%s"`000000
    TMP=`echo "${PORT}" | cut -d'/' -f2`

    # skip lines with category only
    if [ ! -n "${TMP}" ]; then
        echo "Skipping ${PORT}"
        continue;
    fi

    # skip commits to Mk
    if [ "${TMP}" = "Mk" ]; then
        continue;
    fi

    BUILDDATE=`date "+%Y%m%d%H%M%S"`
    RAND=`hexdump -n2 -e\"%u\" /dev/random`
    BUILDID=${BUILDDATE}-${RAND}

    SQLCMD=`printf "INSERT INTO buildqueue (id, owner, repository, revision, status, priority, startdate, enddate, description) VALUES ('%s', '%s', %d, %d, %d, %d, %d, %d, '%s');" "${BUILDID}" "${USER}" ${REPOSITORYID} ${REV} 10 ${PRIORITY} ${START} 0 "Subversion commit"`

    for GROUP in `echo "SELECT buildgroup FROM automaticbuildgroups WHERE username = '${USER}'" | psql -A -t -q ${DBNAME} ${DBUSER}`
    do
        SQLCMD2=`printf "INSERT INTO builds (queueid, backendkey, buildgroup, portname, status, buildstatus, buildreason, buildlog, wrkdir, backendid, startdate, enddate) VALUES ('%s', SUBSTRING(MD5(RANDOM()::text), 1, 25), '%s', '%s', %d, null, null, null, null, 0, 0, 0);" "${BUILDID}" "${GROUP}" "${PORT}" 20`

        SQLCMD="${SQLCMD} ${SQLCMD2}"
    done

    SQLCMD="BEGIN; ${SQLCMD} COMMIT;"

    echo ${SQLCMD} | psql -q ${DBNAME} ${DBUSER}
    if [ $? != 0 ]; then
        echo "ERROR: Failed adding ${PORT} with r${REV} to buildqueue"
    else
        echo "Added ${PORT} with r${REV} to buildqueue"
    fi
done

exit 0
