#!/bin/sh

#
# RedPorts Subversion post-commit hook script
#
# $Id$
#

PATH=${PATH}:/usr/local/bin

REPOSITORYROOT="https://svn.redports.org/"
PRIORITY=7
DBNAME=trac
DBUSER=trac

BUILDDATE=`date "+%Y%m%d%H%M%S"`
RAND=`hexdump -n2 -e\"%u\" /dev/random`
BUILDID=${BUILDDATE}-${RAND}
START=`date +"%s"`000000

if [ -z "${1}" -o -z "${2}" ]; then
    echo "Usage: rpaddcommit <repository> <revision>"
    exit 1
fi

REPOS=$1
REV=$2
USER=`svnlook author -r ${REV} ${REPOS} 2>/dev/null`
COMMITROOT=`svnlook changed -r ${REV} ${REPOS} | cut -b5- | cut -d'/' -f1 | uniq`

if [ -z "${USER}" ]; then
    echo "Invalid revision number"
    exit 1
fi

SQL=`printf "SELECT id FROM portrepositories WHERE type = 'svn' AND (username = '%s' OR username IS NULL) AND replace(url, '%%OWNER%%', '%s') = '%s';" "${USER}" "${USER}" "${REPOSITORYROOT}${COMMITROOT}"`

echo "${SQL}"
REPOSITORYID=`echo "${SQL}" | psql -qtA ${DBNAME} ${DBUSER}`

if [ -z "${REPOSITORYID}" ]; then
    echo "Could not determine RepositoryID"
    exit 1
fi

SQLBUILDQUEUE=`printf "INSERT INTO buildqueue (id, owner, repository, revision, status, priority, startdate, enddate, description) VALUES ('%s', '%s', %d, %d, %d, %d, %d, %d, '%s');" "${BUILDID}" "${USER}" ${REPOSITORYID} ${REV} 10 ${PRIORITY} ${START} 0 "Subversion commit"`
SQLBUILDS=""

# add affected ports to buildqueue
for PORT in `svnlook changed ${REPOS} -r ${REV} | grep -v "D   " | cut -b5- | cut -d'/' -f2-3 | uniq`
do
    TMP=`echo "${PORT}" | cut -d'/' -f2`

    # skip lines with category only
    if [ ! -n "${TMP}" ]; then
        echo "Skipping ${PORT}"
        continue;
    fi

    # skip commits to Mk
    if [ "${TMP}" = "Mk" ]; then
        continue;
    fi

    SQL=""
    for GROUP in `echo "SELECT buildgroup FROM automaticbuildgroups WHERE username = '${USER}' ORDER BY priority" | psql -A -t -q ${DBNAME} ${DBUSER}`
    do
        SQL=`printf "INSERT INTO builds (queueid, backendkey, buildgroup, portname, status, buildstatus, buildreason, buildlog, wrkdir, backendid, startdate, enddate, checkdate) VALUES ('%s', SUBSTRING(MD5(RANDOM()::text), 1, 25), '%s', '%s', %d, null, null, null, null, 0, 0, 0, 0);" "${BUILDID}" "${GROUP}" "${PORT}" 20`

        SQLBUILDS="${SQLBUILDS} ${SQL}"
    done

    if [ ! -z "${SQL}" ]; then
        echo "Schedule build of ${PORT} with r${REV}"
    fi
done

if [ -z "${SQLBUILDS}" ]; then
    echo "Nothing to schedule"
else
    echo "BEGIN; ${SQLBUILDQUEUE} ${SQLBUILDS} COMMIT;" | psql -q ${DBNAME} ${DBUSER}
    if [ $? != 0 ]; then
        echo "ERROR: commit failed!"
        exit 1
    fi
fi

exit 0
