#!/bin/sh

# RedPorts tinderbox backend
#
# $Id$
#
# /tmp/rptinderbox/.lock              Global lock for maintenance
# /tmp/rptinderbox/<build>/.lock      Build lock including shellscript variables
# /tmp/rptinderbox/<build>/.checkout  Checkout done
# /tmp/rptinderbox/<build>/.build     Build started
# /tmp/rptinderbox/<build>/.finished  Build finished
# /tmp/rptinderbox/<build>/ports/     Portstree overlay
#
# /usr/local/tinderbox/portstrees/<portstree>/ports/   Tinderbox portstree
# 

ZFSROOT="zroot/tinderbox/%s/portstree"

WRKBASE=/tmp/rptinderbox
TINDERBOX=/usr/local/tinderbox

checkout()
{
  REPOSITORY=$1
  REVISION=$2
  BUILD=$3

  if [ -f "${WRKBASE}/.lock" ]; then
    echo "Maintenance lock exists."
    return 1
  fi

  LOCK=${WRKBASE}/${BUILD}/.lock

  if [ -f "${LOCK}" ]; then
    echo "Lock ${LOCK} exists."
    return 1
  fi

  if [ ! -d "${WRKBASE}/${BUILD}" ]; then
    mkdir -p ${WRKBASE}/${BUILD} || return 1
  fi

  # create build lock
  touch ${LOCK} || return 1

  PORTSTREE=`${TINDERBOX}/scripts/tc getPortsTreeForBuild -b ${BUILD} 2>/dev/null`

  if [ -z "${PORTSTREE}" ]; then
    echo "Unknown portstree for build ${BUILD}"
    return 1
  fi

  # populate lock
  echo "REPOSITORY=\"${REPOSITORY}\"" >> ${LOCK}
  echo "REVISION=\"${REVISION}\"" >> ${LOCK}
  echo "BUILD=\"${BUILD}\"" >> ${LOCK}
  echo "PORTSTREE=\"${PORTSTREE}\"" >> ${LOCK}
  echo "LOCK=\"${LOCK}\"" >> ${LOCK}

  # checkout overlay ports
  svn export --non-interactive --revision ${REVISION} ${REPOSITORY} ${WRKBASE}/${BUILD}/ports || return 2

  # create snapshot of original tree
  ZFSVOLUME=`printf "${ZFSROOT}" ${PORTSTREE}`
  zfs snapshot ${ZFSVOLUME}@work || return 3

  # apply overlay ports
  find ${WRKBASE}/${BUILD}/ports -type d -d 2 | sed -e "s|^${WRKBASE}/${BUILD}/ports/|${TINDERBOX}/portstrees/${PORTSTREE}/ports/|" | xargs rm -Rf || return 1
  cp -pr ${WRKBASE}/${BUILD}/ports/* ${TINDERBOX}/portstrees/${PORTSTREE}/ports/
  
  # checkout finished
  touch ${WRKBASE}/${BUILD}/.checkout || return 1
  
  return 0
}

clean()
{
  BUILD=$1
  LOCK=${WRKBASE}/${BUILD}/.lock

  if [ ! -f "${LOCK}" ]; then
    echo "No lock for build ${BUILD}"
    return 1
  fi

  . ${LOCK}

  if [ -f "${WRKBASE}/${BUILD}/.build" ]; then
      if [ ! -f "${WRKBASE}/${BUILD}/.finished" ]; then
        ${TINDERBOX}/scripts/tc rmBuildPortsQueueEntry -b ${BUILD} -d ${PORT}
      fi
  fi

  ZFSVOLUME=`printf "${ZFSROOT}" ${PORTSTREE}`
  zfs rollback ${ZFSVOLUME}@work
  zfs destroy ${ZFSVOLUME}@work

  if [ -f "${WRKBASE}/${BUILD}/.build" ]; then
    NEWPACKAGES=`find ${TINDERBOX}/packages/${PORTSTREE}/All/ -type f -newermt "${LASTPACKAGEDATE}" -print`

    for package in ${NEWPACKAGES}
    do
      PKGPORT=`pkg_info -oq ${TINDERBOX}/packages/${PORTSTREE}/All/${package}`
        
      if [ ! -z "${CLEANROOM_MODE}" ]; then
        if [ -d "${WRKBASE}/${BUILD}/ports/${PKGPORT}" ]; then
          rm ${TINDERBOX}/packages/${PORTSTREE}/${PKGPORT%${PKGPORT##*/}}/${package}
          rm ${TINDERBOX}/packages/${PORTSTREE}/All/${package}
        fi
      else
        if [ "${PKGPORT}" = "${PORT}" ]; then
          rm ${TINDERBOX}/packages/${PORTSTREE}/${PKGPORT%${PKGPORT##*/}}/${package}
          rm ${TINDERBOX}/packages/${PORTSTREE}/All/${package}
        fi
      fi
    done
  fi

  rm -rf ${WRKBASE}/${BUILD} || return 1

  return 0
}

build()
{
  PORT=$1
  BUILD=$2
  PRIORITY=$3
  LOCK=${WRKBASE}/${BUILD}/.lock

  if [ -f "${WRKBASE}/.lock" ]; then
    echo "Maintenance lock exists."
    return 1
  fi

  if [ ! -f "${LOCK}" ]; then
    echo "No lock for build ${BUILD}"
    return 1
  fi

  . ${LOCK}

  if [ ! -f "${WRKBASE}/${BUILD}/.checkout" ]; then
    echo "No checkout for build ${BUILD}"
    return 1
  fi

  if [ -f "${WRKBASE}/${BUILD}/.build" ]; then
    echo "Build already running"
    return 1
  fi

  if [ -f "${WRKBASE}/${BUILD}/.finished" ]; then
    echo "Build already finished"
    return 1
  fi

  # aktuellstes package von build merken
  if [ -d "${TINDERBOX}/packages/${BUILD}/All" ]; then
    LASTPACKAGE=`ls -tr ${TINDERBOX}/packages/${BUILD}/All | tail -1`
    LASTPACKAGEDATE=`stat -f %m ${TINDERBOX}/packages/${BUILD}/All/${LASTPACKAGE}`
    LASTPACKAGEDATE=`date -r ${LASTPACKAGEDATE} "+%Y-%m-%d %H:%M:%S"`
  else
    LASTPACKAGE=""
    LASTPACKAGEDATE=`date "+%Y-%m-%d %H:%M:%S"`
  fi

  echo "PORT=\"${PORT}\"" >> ${LOCK}
  echo "PRIORITY=\"${PRIORITY}\"" >> ${LOCK}
  echo "LASTPACKAGE=\"${LASTPACKAGE}\"" >> ${LOCK}
  echo "LASTPACKAGEDATE=\"${LASTPACKAGEDATE}\"" >> ${LOCK}

  ${TINDERBOX}/scripts/tc addBuildPortsQueueEntry -b ${BUILD} -d ${PORT} -p ${PRIORITY} 2>/dev/null || return 1

  touch ${WRKBASE}/${BUILD}/.build || return 1

  return 0
}

status()
{
  BUILD=$1

  if [ ! -d "${WRKBASE}/${BUILD}" ]; then
    echo "STATUS=unknown"
    return 1
  fi

  if [ -f "${WRKBASE}/${BUILD}/.finished" ]; then
    . ${WRKBASE}/${BUILD}/.finished

    echo "STATUS=${STATUS}"

    if [ -n "${FAIL_REASON}" ]; then
      echo "FAIL_REASON=${FAIL_REASON}"
    fi

    echo "BUILDLOG=${BUILDLOG}"

    if [ -n "${WRKDIR}" ]; then
      echo "WRKDIR=${WRKDIR}"
    fi
    return 0
  fi

  if [ -f "${WRKBASE}/${BUILD}/.build" ]; then
    echo "STATUS=building"
    return 0
  fi

  if [ -f "${WRKBASE}/${BUILD}/.lock" ]; then
    echo "STATUS=used"
    return 0
  fi

  echo "STATUS=idle"
  return 0
}


case "$1" in
'build')
  if build $2 $3 $4 2>&1 ; then
    echo "OK"
    return 0
  else
    echo "ERROR"
    return 1
  fi
;;
'checkout')
  if checkout $2 $3 $4 2>&1 ; then
    echo "OK"
    return 0
  else
    echo "ERROR"
    return 1
  fi
;;
'clean')
  if clean $2 2>&1 ; then
    echo "OK"
    return 0
  else
    echo "ERROR"
    return 1
  fi
  return $?
;;
'status')
  if status $2 2>&1 ; then
    echo "OK"
    return 0
  else
    echo "ERROR"
    return 1
  fi
;;
*)
  echo "Usage: $0 [build|checkout|clean|status] param"
  exit 1
;;
esac

exit 0
